// Building definitions: static data for every buildable structure.
// Fields not relevant to a building are 0, null, false or {}.
//
// Field reference:
//   cost          resources needed to build ({ wood?, metal? })
//   category      build-menu category id (see CATEGORIES)
//   produces      per-day resource output ({ food?, water?, energy? })
//   consumes      per-day fuel needed to run ({ water?, wood? }); without it
//                 the building stalls (no production, no consumption)
//   jobs          worker slots; output scales with assigned workers
//   houses        survivor housing slots
//   requiresEnergy  energy drained per day from the grid; powered while energy > 0
//   energyDayOnly produces energy only during the day phase (solar)
//   capBonus      extra storage capacity per resource ({ energy?, water?, ... })
//   extracts      map node type the building depletes ('forest'|'ruins'|'ore')
//   extractRate   per-day amount taken from the node
//   plants        map node type the building regrows (forester)
//   researchRate  per-day research points produced
//   requiresTech  tech id that must be researched before building
//   isWall        blocks zombie pathing until destroyed
//   isTower       shoots zombies automatically
//   isTrap        damages zombies walking over it
//   trapDamage    damage dealt per trigger (traps)
//
// Optional field (not part of the required schema):
//   proximity     site-efficiency rule { tile: 'water'|'forest'|'wildlife',
//                 range, poor }: output is full when such a tile lies within
//                 `range` of the footprint, scaled by `poor` otherwise (well,
//                 hunt, fish, ranch)
//   isRoad        road tile: supports drag-placement in a row like walls and
//                 grants the logistics aura (see sim/modifiers.js)
//   modelScaleMul visual-only scale multiplier applied after the footprint
//                 normalization (default 1): gives a building extra presence
//                 (hq), letting it overhang its footprint a little
//   modelWidthFrac visual-only horizontal extent, as a fraction of the
//                 footprint span (default 0.95): thin structures (road)

export const BUILDING_DEFS = {
  hq: {
    id: 'hq',
    name: 'Rifugio',
    desc: 'Il cuore del tuo insediamento. Genera energia anche di notte e ospita quattro sopravvissuti. Se cade, è finita.',
    cost: {},
    category: 'infrastrutture',
    w: 3,
    h: 3,
    hp: 1000,
    produces: { energy: 4 },
    consumes: {},
    jobs: 0,
    houses: 4,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'hq',
    modelScaleMul: 0.5,
  },
  tent: {
    id: 'tent',
    name: 'Tenda',
    desc: 'Un riparo di fortuna per due sopravvissuti.',
    cost: { wood: 15 },
    category: 'abitazioni',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 2,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'tent',
  },
  shack: {
    id: 'shack',
    name: 'Baracca',
    desc: 'Una baracca di lamiera che ospita tre sopravvissuti. Economica ma fragile.',
    cost: { wood: 10 },
    category: 'abitazioni',
    w: 1,
    h: 1,
    hp: 80,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 3,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'shack',
  },
  house: {
    id: 'house',
    name: 'Casa',
    desc: 'Una casa solida che ospita quattro sopravvissuti.',
    cost: { wood: 25, metal: 10 },
    category: 'abitazioni',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 4,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'house',
  },
  farm: {
    id: 'farm',
    name: 'Fattoria',
    desc: 'Coltiva cibo ogni giorno, ma consuma acqua. Richiede due lavoratori.',
    cost: { wood: 30 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 150,
    produces: { food: 8 },
    consumes: { water: 3 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'farm',
  },
  garden: {
    id: 'garden',
    name: 'Orto',
    desc: 'Un piccolo orto che produce cibo con poca acqua. Richiede un lavoratore.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 4 },
    consumes: { water: 2 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'garden',
  },
  greenhouse: {
    id: 'greenhouse',
    name: 'Serra',
    desc: 'Una serra riscaldata ad alta resa. Richiede energia, acqua e due lavoratori.',
    cost: { wood: 40, metal: 20 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 180,
    produces: { food: 14 },
    consumes: { water: 5 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'greenhouse',
  },
  rain: {
    id: 'rain',
    name: 'Raccoglitore di pioggia',
    desc: 'Raccoglie la preziosa acqua piovana. Rende molto di più quando piove, pochissimo durante le ondate di calore.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 80,
    produces: { water: 4 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'rain-collector',
  },
  well: {
    id: 'well',
    name: 'Pozzo',
    desc: 'Attinge alle falde acquifere in automatico, senza lavoratori. Rende di più vicino all\'acqua.',
    cost: { wood: 20, metal: 10 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { water: 8 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'well',
    proximity: { tile: 'water', range: 3, poor: 0.4 },
  },
  cistern: {
    id: 'cistern',
    name: 'Cisterna',
    desc: 'Una cisterna che filtra acqua e ne aumenta la capacità di stoccaggio.',
    cost: { metal: 25 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 150,
    produces: { water: 2 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { water: 60 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'cistern',
  },
  hunt: {
    id: 'hunt',
    name: 'Capanno da caccia',
    desc: 'Caccia la selvaggina dei dintorni. Rende di più vicino alla foresta. Richiede un lavoratore.',
    cost: { wood: 20 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 6 },
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'hunt',
    proximity: { tile: 'forest', range: 3, poor: 0.5 },
  },
  fish: {
    id: 'fish',
    name: 'Capanno da pesca',
    desc: 'Pesca nelle acque dei dintorni. Rende di più vicino all\'acqua. Richiede un lavoratore.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 5 },
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'fish',
    proximity: { tile: 'water', range: 2, poor: 0.5 },
  },
  ranch: {
    id: 'ranch',
    name: 'Allevamento',
    desc: 'Alza animali catturati dalle mandrie selvatiche dei dintorni: rende di più vicino a una mandria. Finché è staffato, gli animali da lavoro danno una mano in fattoria e nei trasporti. Richiede due lavoratori.',
    cost: { wood: 40 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 150,
    produces: { food: 6 },
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'ranch',
    proximity: { tile: 'wildlife', range: 3, poor: 0.5 },
  },
  lumber: {
    id: 'lumber',
    name: 'Tagliaboschi',
    desc: 'Taglia gli alberi di una foresta vicina fino a esaurirla. Richiede due lavoratori.',
    cost: { wood: 15 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'forest',
    extractRate: 10,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'lumber',
  },
  forester: {
    id: 'forester',
    name: 'Guardaboschi',
    desc: 'Pianta nuovi alberi per rigenerare una foresta esaurita. Richiede un lavoratore.',
    cost: { wood: 20 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: 'forest',
    researchRate: 0,
    requiresTech: 'forestry',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'forester',
  },
  scavenger: {
    id: 'scavenger',
    name: 'Rottamatore',
    desc: 'Recupera metallo dalle rovine del vecchio mondo. Richiede due lavoratori.',
    cost: { wood: 25 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 150,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'ruins',
    extractRate: 6,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'scrapyard',
  },
  mine: {
    id: 'mine',
    name: 'Miniera',
    desc: 'Estrae metallo da un filone di minerale. Richiede tre lavoratori.',
    cost: { wood: 30, metal: 20 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 250,
    produces: {},
    consumes: {},
    jobs: 3,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'ore',
    extractRate: 8,
    plants: null,
    researchRate: 0,
    requiresTech: 'mining',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'mine',
  },
  smelter: {
    id: 'smelter',
    name: 'Fonderia',
    desc: 'Fonde rottami e legno in metallo utile. Richiede due lavoratori.',
    cost: { wood: 30, metal: 30 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 250,
    produces: { metal: 3 },
    consumes: { wood: 2 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'smelter',
  },
  distillery: {
    id: 'distillery',
    name: 'Distillatore',
    desc: 'Distilla legno in carburante per i mezzi dell\'insediamento. Senza legna si ferma. Richiede un lavoratore.',
    cost: { wood: 30, metal: 15 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: { fuel: 4 },
    consumes: { wood: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'distillery',
  },
  garage: {
    id: 'garage',
    name: 'Autorimessa',
    desc: 'Tiene in strada i mezzi dell\'insediamento: finché è staffata, l\'estrazione rende il 50% in più. L\'effetto non si cumula. Brucia carburante e richiede un lavoratore.',
    cost: { wood: 40, metal: 30 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: { fuel: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'garage',
  },
  warehouse: {
    id: 'warehouse',
    name: 'Magazzino',
    desc: 'Un magazzino capiente che aumenta lo stoccaggio di cibo, legno e metallo.',
    cost: { wood: 40 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 300,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { food: 100, wood: 100, metal: 100 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'warehouse',
  },
  lab: {
    id: 'lab',
    name: 'Laboratorio',
    desc: 'Studia i reperti del vecchio mondo e produce punti ricerca. Richiede due lavoratori.',
    cost: { wood: 30, metal: 25 },
    category: 'infrastrutture',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 4,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'lab',
  },
  clinic: {
    id: 'clinic',
    name: 'Infermeria',
    desc: 'Cura i sopravvissuti: con almeno un lavoratore, fame e sete crescono più lentamente.',
    cost: { wood: 30, metal: 15 },
    category: 'infrastrutture',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'clinic',
  },
  radio: {
    id: 'radio',
    name: 'Radio di emergenza',
    desc: 'Trasmette richieste di aiuto nel deserto: finché è staffata, un sopravvissuto in più arriva a ogni alba. Richiede un lavoratore.',
    cost: { wood: 30, metal: 20 },
    category: 'infrastrutture',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'radio',
  },
  road: {
    id: 'road',
    name: 'Strada',
    desc: 'Un tratto di strada asfaltata: i trasporti verso i nodi si velocizzano e ogni strada aumenta del 2% l\'estrazione, fino a un massimo del 40%. Si piazza anche trascinando il mouse, come i muri.',
    cost: { wood: 2 },
    category: 'infrastrutture',
    w: 1,
    h: 1,
    hp: 50,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'road',
    isRoad: true,
    modelWidthFrac: 0.25,
  },
  solar: {
    id: 'solar',
    name: 'Pannello solare',
    desc: 'Genera energia, ma solo durante il giorno.',
    cost: { metal: 35 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 80,
    produces: { energy: 5 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: true,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'solar-panel',
  },
  'solar-plant': {
    id: 'solar-plant',
    name: 'Impianto solare',
    desc: 'Un campo di pannelli solari: tanta energia, solo di giorno.',
    cost: { metal: 80 },
    category: 'energia',
    w: 2,
    h: 2,
    hp: 150,
    produces: { energy: 14 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: true,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'solar2',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'solar-plant',
  },
  wind: {
    id: 'wind',
    name: 'Turbina eolica',
    desc: 'Genera energia giorno e notte. Rende di più con pioggia e tempesta.',
    cost: { metal: 45 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: { energy: 3 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'wind-turbine',
  },
  generator: {
    id: 'generator',
    name: 'Generatore',
    desc: 'Brucia legna per generare energia, anche di notte. Richiede un lavoratore.',
    cost: { metal: 40 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: { energy: 6 },
    consumes: { wood: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'generator',
  },
  battery: {
    id: 'battery',
    name: 'Batteria',
    desc: 'Accumula energia in eccesso e aumenta la capacità della rete.',
    cost: { metal: 35 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { energy: 50 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'batteries',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'battery',
  },
  motor: {
    id: 'motor',
    name: 'Motore elettrico',
    desc: 'Un motore che dà una mano agli estrattori: finché la rete è carica producono il 25% in più. L\'effetto non si cumula.',
    cost: { metal: 30 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'motor',
  },
  palisade: {
    id: 'palisade',
    name: 'Palizzata',
    desc: 'Una palizzata di legno: economica e veloce da alzare, ma poco resistente.',
    cost: { wood: 8 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'palisade',
  },
  'scrap-wall': {
    id: 'scrap-wall',
    name: 'Muro di lamiere',
    desc: 'Un muro di lamiere saldate: buona resistenza a costo contenuto.',
    cost: { metal: 15 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 450,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'scrap-wall',
  },
  'brick-wall': {
    id: 'brick-wall',
    name: 'Muro di mattoni',
    desc: 'Un solido muro di mattoni che regge a lungo gli assalti delle orde.',
    cost: { wood: 20 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 800,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'brick-wall',
  },
  'concrete-wall': {
    id: 'concrete-wall',
    name: 'Muro in cemento armato',
    desc: 'Il baluardo definitivo: quasi inattaccabile dagli zombie.',
    cost: { metal: 30 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 1400,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'concrete',
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'concrete-wall',
  },
  tower: {
    id: 'tower',
    name: 'Torre di guardia',
    desc: 'Spara automaticamente agli zombie nel raggio. Richiede energia e un lavoratore.',
    cost: { wood: 20, metal: 30 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: true,
    isTrap: false,
    trapDamage: 0,
    damage: 10,
    range: 6,
    fireRate: 1,
    model: 'tower',
  },
  sniper: {
    id: 'sniper',
    name: 'Torretta automatica',
    desc: 'Una torretta di precisione a lungo raggio. Richiede molta energia e un lavoratore.',
    cost: { metal: 35 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 250,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'ballistics',
    isWall: false,
    isTower: true,
    isTrap: false,
    trapDamage: 0,
    damage: 22,
    range: 8,
    fireRate: 0.8,
    model: 'sniper-tower',
  },
  spotlight: {
    id: 'spotlight',
    name: 'Faro da campo',
    desc: 'Un faro alimentato dalla rete: finché la rete è carica, le torri della colonia infliggono il 20% di danno in più. L\'effetto non si cumula.',
    cost: { wood: 25, metal: 15 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'spotlight',
  },
  streetlamp: {
    id: 'streetlamp',
    name: 'Lampione',
    desc: 'Illumina le vie dell\'insediamento: finché la rete è carica, guarnigioni e milizia infliggono il 25% di danno in più. L\'effetto non si cumula.',
    cost: { wood: 10, metal: 5 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 80,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'streetlamp',
  },
  trap: {
    id: 'trap',
    name: 'Campo di trappole',
    desc: 'Un campo di trappole che ferisce gli zombie di passaggio.',
    cost: { wood: 10 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: true,
    trapDamage: 6,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'trap',
  },
};

/** Build-menu categories, in display order. */
export const CATEGORIES = [
  { id: 'abitazioni', name: 'Abitazioni', icon: '🏠' },
  { id: 'sostentamento', name: 'Sostentamento', icon: '🥫' },
  { id: 'risorse', name: 'Risorse', icon: '🪵' },
  { id: 'energia', name: 'Energia', icon: '⚡' },
  { id: 'difesa', name: 'Difesa', icon: '🛡️' },
  { id: 'infrastrutture', name: 'Infrastrutture', icon: '🏛️' },
];

/** Order in which buildings appear in the build menu, grouped by category. */
export const BUILD_MENU_ORDER = [
  // Abitazioni
  'tent',
  'shack',
  'house',
  // Sostentamento
  'farm',
  'garden',
  'greenhouse',
  'rain',
  'well',
  'cistern',
  'hunt',
  'fish',
  'ranch',
  // Risorse
  'lumber',
  'forester',
  'scavenger',
  'mine',
  'smelter',
  'distillery',
  'garage',
  'warehouse',
  // Energia
  'solar',
  'solar-plant',
  'wind',
  'generator',
  'motor',
  'battery',
  // Difesa
  'palisade',
  'scrap-wall',
  'brick-wall',
  'concrete-wall',
  'tower',
  'sniper',
  'spotlight',
  'streetlamp',
  'trap',
  // Infrastrutture
  'lab',
  'clinic',
  'radio',
  'road',
];

/**
 * Returns the definition for a building id.
 * @param {string} id
 * @returns {object | undefined}
 */
export function getDef(id) {
  return BUILDING_DEFS[id];
}
