// Building definitions: static data for every buildable structure.
// Fields not relevant to a building are 0, null, false or {}.
//
// Field reference:
//   cost          resources needed to build ({ wood?, metal? })
//   category      build-menu category id (see CATEGORIES)
//   produces      per-day resource output ({ food?, water?, energy? })
//   consumes      per-day fuel needed to run ({ water?, wood? }); without it
//                 the building stalls (no production, no consumption)
//   jobs          worker slots; output scales with assigned workers
//   houses        survivor housing slots
//   requiresEnergy  energy drained per day from the grid; powered while energy > 0
//   energyDayOnly produces energy only during the day phase (solar)
//   capBonus      extra storage capacity per resource ({ energy?, water?, ... })
//   extracts      map node type the building depletes ('forest'|'ruins'|'ore')
//   extractRate   per-day amount taken from the node
//   plants        map node type the building regrows (forester)
//   researchRate  per-day research points produced
//   requiresTech  tech id that must be researched before building
//   isWall        blocks zombie pathing until destroyed
//   isTower       shoots zombies automatically
//   isTrap        damages zombies walking over it
//   trapDamage    damage dealt per trigger (traps)
//
// Optional field (not part of the required schema):
//   proximity     site-efficiency rule { tile: 'water'|'forest'|'wildlife',
//                 range, poor }: output is full when such a tile lies within
//                 `range` of the footprint, scaled by `poor` otherwise (well,
//                 hunt, fish, ranch)
//   isRoad        road tile: supports drag-placement in a row like walls and
//                 grants the logistics aura (see sim/modifiers.js)
//   modelScaleMul visual-only scale multiplier applied after the footprint
//                 normalization (default 1): gives a building extra presence
//                 (hq), letting it overhang its footprint a little
//   modelWidthFrac visual-only horizontal extent, as a fraction of the
//                 footprint span (default 0.95): thin structures (road)

export const BUILDING_DEFS = {
  hq: {
    id: 'hq',
    name: 'Refuge',
    desc: 'The heart of your settlement. Generates energy even at night and houses four survivors. If it falls, it\'s over.',
    cost: {},
    category: 'infrastrutture',
    w: 3,
    h: 3,
    hp: 1000,
    produces: { energy: 4 },
    consumes: {},
    jobs: 0,
    houses: 4,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'hq',
    modelScaleMul: 0.5,
  },
  tent: {
    id: 'tent',
    name: 'Tent',
    desc: 'A makeshift shelter for two survivors.',
    cost: { wood: 15 },
    category: 'abitazioni',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 2,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'tent',
  },
  shack: {
    id: 'shack',
    name: 'Shack',
    desc: 'A sheet-metal shack that houses three survivors. Cheap but fragile.',
    cost: { wood: 10 },
    category: 'abitazioni',
    w: 1,
    h: 1,
    hp: 80,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 3,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'shack',
  },
  house: {
    id: 'house',
    name: 'House',
    desc: 'A solid house that houses four survivors.',
    cost: { wood: 25, metal: 10 },
    category: 'abitazioni',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 4,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'house',
  },
  farm: {
    id: 'farm',
    name: 'Farm',
    desc: 'Grows food every day, but consumes water. Requires two workers.',
    cost: { wood: 30 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 150,
    produces: { food: 8 },
    consumes: { water: 3 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'farm',
  },
  garden: {
    id: 'garden',
    name: 'Garden',
    desc: 'A small garden that produces food with little water. Requires one worker.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 4 },
    consumes: { water: 2 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'garden',
  },
  greenhouse: {
    id: 'greenhouse',
    name: 'Greenhouse',
    desc: 'A heated, high-yield greenhouse. Requires energy, water and two workers.',
    cost: { wood: 40, metal: 20 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 180,
    produces: { food: 14 },
    consumes: { water: 5 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'greenhouse',
  },
  rain: {
    id: 'rain',
    name: 'Rain Collector',
    desc: 'Collects precious rainwater. Yields much more when it rains, very little during heat waves.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 80,
    produces: { water: 4 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'rain-collector',
  },
  well: {
    id: 'well',
    name: 'Well',
    desc: 'Draws from the water table automatically, no workers needed. Yields more near water.',
    cost: { wood: 20, metal: 10 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { water: 8 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'well',
    proximity: { tile: 'water', range: 3, poor: 0.4 },
  },
  cistern: {
    id: 'cistern',
    name: 'Cistern',
    desc: 'A cistern that filters water and increases water storage capacity.',
    cost: { metal: 25 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 150,
    produces: { water: 2 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { water: 60 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'cistern',
  },
  hunt: {
    id: 'hunt',
    name: 'Hunting Cabin',
    desc: 'Hunts game in the surrounding area. Yields more near the forest. Requires one worker.',
    cost: { wood: 20 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 6 },
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'hunt',
    proximity: { tile: 'forest', range: 3, poor: 0.5 },
  },
  fish: {
    id: 'fish',
    name: 'Fishing Cabin',
    desc: 'Fishes the surrounding waters. Yields more near water. Requires one worker.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 5 },
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'fish',
    proximity: { tile: 'water', range: 2, poor: 0.5 },
  },
  ranch: {
    id: 'ranch',
    name: 'Ranch',
    desc: 'Raises animals caught from the nearby wild herds: yields more near a herd. While staffed, work animals lend a hand on farms and in hauling. Requires two workers.',
    cost: { wood: 40 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 150,
    produces: { food: 6 },
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'ranch',
    proximity: { tile: 'wildlife', range: 3, poor: 0.5 },
  },
  lumber: {
    id: 'lumber',
    name: 'Lumberjack',
    desc: 'Cuts the trees of a nearby forest until it is depleted. Requires two workers.',
    cost: { wood: 15 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'forest',
    extractRate: 10,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'lumber',
  },
  forester: {
    id: 'forester',
    name: 'Forester',
    desc: 'Plants new trees to regrow a depleted forest. Requires one worker.',
    cost: { wood: 20 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: 'forest',
    researchRate: 0,
    requiresTech: 'forestry',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'forester',
  },
  scavenger: {
    id: 'scavenger',
    name: 'Scavenger',
    desc: 'Recovers metal from the ruins of the old world. Requires two workers.',
    cost: { wood: 25 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 150,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'ruins',
    extractRate: 6,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'scrapyard',
  },
  mine: {
    id: 'mine',
    name: 'Mine',
    desc: 'Extracts metal from an ore vein. Requires three workers.',
    cost: { wood: 30, metal: 20 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 250,
    produces: {},
    consumes: {},
    jobs: 3,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'ore',
    extractRate: 8,
    plants: null,
    researchRate: 0,
    requiresTech: 'mining',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'mine',
  },
  smelter: {
    id: 'smelter',
    name: 'Smelter',
    desc: 'Smelts scrap and wood into usable metal. Requires two workers.',
    cost: { wood: 30, metal: 30 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 250,
    produces: { metal: 3 },
    consumes: { wood: 2 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'smelter',
  },
  distillery: {
    id: 'distillery',
    name: 'Distillery',
    desc: 'Distills wood into fuel for the settlement\'s vehicles. Without wood it stalls. Requires one worker.',
    cost: { wood: 30, metal: 15 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: { fuel: 4 },
    consumes: { wood: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'distillery',
  },
  garage: {
    id: 'garage',
    name: 'Garage',
    desc: 'Keeps the settlement\'s vehicles on the road: while staffed, extraction yields 50% more. The effect does not stack. Burns fuel and requires one worker.',
    cost: { wood: 40, metal: 30 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: { fuel: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'garage',
  },
  warehouse: {
    id: 'warehouse',
    name: 'Warehouse',
    desc: 'A spacious warehouse that increases food, wood and metal storage.',
    cost: { wood: 40 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 300,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { food: 100, wood: 100, metal: 100 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'warehouse',
  },
  lab: {
    id: 'lab',
    name: 'Laboratory',
    desc: 'Studies artifacts of the old world and produces research points. Requires two workers.',
    cost: { wood: 30, metal: 25 },
    category: 'infrastrutture',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 4,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'lab',
  },
  clinic: {
    id: 'clinic',
    name: 'Clinic',
    desc: 'Cares for survivors: with at least one worker, hunger and thirst grow more slowly.',
    cost: { wood: 30, metal: 15 },
    category: 'infrastrutture',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'clinic',
  },
  radio: {
    id: 'radio',
    name: 'Emergency Radio',
    desc: 'Broadcasts calls for help into the desert: while staffed, one extra survivor arrives at each dawn. Requires one worker.',
    cost: { wood: 30, metal: 20 },
    category: 'infrastrutture',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'radio',
  },
  road: {
    id: 'road',
    name: 'Road',
    desc: 'A stretch of paved road: hauling to nodes speeds up and each road increases extraction by 2%, up to a maximum of 40%. Can also be placed by dragging the mouse, like walls.',
    cost: { wood: 2 },
    category: 'infrastrutture',
    w: 1,
    h: 1,
    hp: 50,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'road',
    isRoad: true,
    modelWidthFrac: 0.25,
  },
  solar: {
    id: 'solar',
    name: 'Solar Panel',
    desc: 'Generates energy, but only during the day.',
    cost: { metal: 35 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 80,
    produces: { energy: 5 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: true,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'solar-panel',
  },
  'solar-plant': {
    id: 'solar-plant',
    name: 'Solar Plant',
    desc: 'A field of solar panels: plenty of energy, only by day.',
    cost: { metal: 80 },
    category: 'energia',
    w: 2,
    h: 2,
    hp: 150,
    produces: { energy: 14 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: true,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'solar2',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'solar-plant',
  },
  wind: {
    id: 'wind',
    name: 'Wind Turbine',
    desc: 'Generates energy day and night. Yields more in rain and storms.',
    cost: { metal: 45 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: { energy: 3 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'wind-turbine',
  },
  generator: {
    id: 'generator',
    name: 'Generator',
    desc: 'Burns wood to generate energy, even at night. Requires one worker.',
    cost: { metal: 40 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: { energy: 6 },
    consumes: { wood: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'generator',
  },
  battery: {
    id: 'battery',
    name: 'Battery',
    desc: 'Stores excess energy and increases the grid\'s capacity.',
    cost: { metal: 35 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { energy: 50 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'batteries',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'battery',
  },
  motor: {
    id: 'motor',
    name: 'Electric Motor',
    desc: 'A motor that lends a hand to the extractors: while the grid is charged they produce 25% more. The effect does not stack.',
    cost: { metal: 30 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'motor',
  },
  palisade: {
    id: 'palisade',
    name: 'Palisade',
    desc: 'A wooden palisade: cheap and quick to raise, but not very sturdy.',
    cost: { wood: 8 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'palisade',
  },
  'scrap-wall': {
    id: 'scrap-wall',
    name: 'Scrap Wall',
    desc: 'A wall of welded sheet metal: good durability at a modest cost.',
    cost: { metal: 15 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 450,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'scrap-wall',
  },
  'brick-wall': {
    id: 'brick-wall',
    name: 'Brick Wall',
    desc: 'A solid brick wall that withstands horde assaults for a long time.',
    cost: { wood: 20 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 800,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'brick-wall',
  },
  'concrete-wall': {
    id: 'concrete-wall',
    name: 'Concrete Wall',
    desc: 'The ultimate bulwark: nearly impervious to zombie attacks.',
    cost: { metal: 30 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 1400,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'concrete',
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'concrete-wall',
  },
  tower: {
    id: 'tower',
    name: 'Watch Tower',
    desc: 'Automatically shoots zombies within range. Requires energy and one worker.',
    cost: { wood: 20, metal: 30 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: true,
    isTrap: false,
    trapDamage: 0,
    damage: 10,
    range: 6,
    fireRate: 1,
    model: 'tower',
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper Turret',
    desc: 'A long-range precision turret. Requires a lot of energy and one worker.',
    cost: { metal: 35 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 250,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'ballistics',
    isWall: false,
    isTower: true,
    isTrap: false,
    trapDamage: 0,
    damage: 22,
    range: 8,
    fireRate: 0.8,
    model: 'sniper-tower',
  },
  spotlight: {
    id: 'spotlight',
    name: 'Field Spotlight',
    desc: 'A grid-powered spotlight: while the grid is charged, the colony\'s towers deal 20% more damage. The effect does not stack.',
    cost: { wood: 25, metal: 15 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'spotlight',
  },
  streetlamp: {
    id: 'streetlamp',
    name: 'Street Lamp',
    desc: 'Lights up the settlement\'s streets: while the grid is charged, garrisons and militia deal 25% more damage. The effect does not stack.',
    cost: { wood: 10, metal: 5 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 80,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'streetlamp',
  },
  trap: {
    id: 'trap',
    name: 'Trap Field',
    desc: 'A field of traps that wounds passing zombies.',
    cost: { wood: 10 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: true,
    trapDamage: 6,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'trap',
  },
};

/** Build-menu categories, in display order. */
export const CATEGORIES = [
  { id: 'abitazioni', name: 'Housing', icon: '🏠' },
  { id: 'sostentamento', name: 'Sustenance', icon: '🥫' },
  { id: 'risorse', name: 'Resources', icon: '🪵' },
  { id: 'energia', name: 'Energy', icon: '⚡' },
  { id: 'difesa', name: 'Defense', icon: '🛡️' },
  { id: 'infrastrutture', name: 'Infrastructure', icon: '🏛️' },
];

/** Order in which buildings appear in the build menu, grouped by category. */
export const BUILD_MENU_ORDER = [
  // Abitazioni
  'tent',
  'shack',
  'house',
  // Sostentamento
  'farm',
  'garden',
  'greenhouse',
  'rain',
  'well',
  'cistern',
  'hunt',
  'fish',
  'ranch',
  // Risorse
  'lumber',
  'forester',
  'scavenger',
  'mine',
  'smelter',
  'distillery',
  'garage',
  'warehouse',
  // Energia
  'solar',
  'solar-plant',
  'wind',
  'generator',
  'motor',
  'battery',
  // Difesa
  'palisade',
  'scrap-wall',
  'brick-wall',
  'concrete-wall',
  'tower',
  'sniper',
  'spotlight',
  'streetlamp',
  'trap',
  // Infrastrutture
  'lab',
  'clinic',
  'radio',
  'road',
];

/**
 * Returns the definition for a building id.
 * @param {string} id
 * @returns {object | undefined}
 */
export function getDef(id) {
  return BUILDING_DEFS[id];
}
